"""initial schema

Revision ID: 001_initial
Revises:
Create Date: 2026-07-25 21:48:52.124561
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_versions",
        sa.Column("assistant_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("graph_id", sa.String(length=256), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("assistant_id", "version"),
    )
    op.create_table(
        "assistants",
        sa.Column("assistant_id", sa.UUID(), nullable=False),
        sa.Column("graph_id", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("assistant_id"),
    )
    op.create_index("ix_assistants_created_at", "assistants", ["created_at"], unique=False)
    op.create_index("ix_assistants_graph_id", "assistants", ["graph_id"], unique=False)
    op.create_index(
        "ix_assistants_metadata_gin",
        "assistants",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"metadata": "jsonb_path_ops"},
    )
    op.create_table(
        "crons",
        sa.Column("cron_id", sa.UUID(), nullable=False),
        sa.Column("assistant_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("schedule", sa.String(length=128), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("next_run_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.String(length=256), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("on_run_completed", sa.String(length=16), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("cron_id"),
    )
    op.create_index("ix_crons_assistant_id", "crons", ["assistant_id"], unique=False)
    op.create_index(
        "ix_crons_enabled_next_run", "crons", ["enabled", "next_run_date"], unique=False
    )
    op.create_index(
        "ix_crons_metadata_gin",
        "crons",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"metadata": "jsonb_path_ops"},
    )
    op.create_index("ix_crons_thread_id", "crons", ["thread_id"], unique=False)
    op.create_table(
        "retry_counters",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "runs",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.UUID(), nullable=True),
        sa.Column("assistant_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "kwargs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("multitask_strategy", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index("ix_runs_assistant_id_status", "runs", ["assistant_id", "status"], unique=False)
    op.create_index("ix_runs_status_created_at", "runs", ["status", "created_at"], unique=False)
    op.create_index(
        "ix_runs_thread_id_created_at", "runs", ["thread_id", "created_at"], unique=False
    )
    op.create_index("ix_runs_thread_id_status", "runs", ["thread_id", "status"], unique=False)
    op.create_index(
        "uq_runs_one_running_per_thread",
        "runs",
        ["thread_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running' AND thread_id IS NOT NULL"),
    )
    op.create_table(
        "store_items",
        sa.Column("prefix", sa.Text(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("prefix", "key"),
    )
    op.create_table(
        "threads",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "interrupts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("state_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("thread_id"),
    )
    op.create_index(
        "ix_threads_metadata_gin",
        "threads",
        ["metadata"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"metadata": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_threads_status_updated_at", "threads", ["status", "updated_at"], unique=False
    )
    op.create_index("ix_threads_updated_at", "threads", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_threads_updated_at", table_name="threads")
    op.drop_index("ix_threads_status_updated_at", table_name="threads")
    op.drop_index(
        "ix_threads_metadata_gin",
        table_name="threads",
        postgresql_using="gin",
        postgresql_ops={"metadata": "jsonb_path_ops"},
    )
    op.drop_table("threads")
    op.drop_table("store_items")
    op.drop_index(
        "uq_runs_one_running_per_thread",
        table_name="runs",
        postgresql_where=sa.text("status = 'running' AND thread_id IS NOT NULL"),
    )
    op.drop_index("ix_runs_thread_id_status", table_name="runs")
    op.drop_index("ix_runs_thread_id_created_at", table_name="runs")
    op.drop_index("ix_runs_status_created_at", table_name="runs")
    op.drop_index("ix_runs_assistant_id_status", table_name="runs")
    op.drop_table("runs")
    op.drop_table("retry_counters")
    op.drop_index("ix_crons_thread_id", table_name="crons")
    op.drop_index(
        "ix_crons_metadata_gin",
        table_name="crons",
        postgresql_using="gin",
        postgresql_ops={"metadata": "jsonb_path_ops"},
    )
    op.drop_index("ix_crons_enabled_next_run", table_name="crons")
    op.drop_index("ix_crons_assistant_id", table_name="crons")
    op.drop_table("crons")
    op.drop_index(
        "ix_assistants_metadata_gin",
        table_name="assistants",
        postgresql_using="gin",
        postgresql_ops={"metadata": "jsonb_path_ops"},
    )
    op.drop_index("ix_assistants_graph_id", table_name="assistants")
    op.drop_index("ix_assistants_created_at", table_name="assistants")
    op.drop_table("assistants")
    op.drop_table("assistant_versions")
    # ### end Alembic commands ###
